const ProductConstant = {
    ADD_PRODUCT : 'ADD_PRODUCT',
    INCREASE_COUNT: 'INCREASE_COUNT',
    DECREASE_COUNT: 'DECREASE_COUNT',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    GET_TOTAL_DISCOUNT: 'GET_TOTAL_DISCOUNT',
    GET_TOTAL_AMOUNT: 'GET_TOTAL_AMOUNT'
}
export default ProductConstant;